#!/usr/bin/env bash
# ensure-hermes-ui-proxy.sh — loopback nginx proxy that injects the Hermes
# dashboard session token, so operators can use the FULL native dashboard in a
# browser over `ssh -L`. Hermes 0.19.0 requires an Authorization: Bearer header
# that a browser cannot send on navigation; this supplies it server-side.
#
# One listener per hermes-dashboard*.service, port = upstream + 100.
# The token lives in ONE mode-600 include file (mirrors cortex-auth.conf), so
# rotation rewrites one small file. ensure-dashboard-token.sh calls this script
# so the two can never drift.
#
# Env: ORCH_ENV, SYSTEMD_USER_DIR, NGINX_CONF_DIR, NGINX_AUTH_FILE,
#      ENSURE_UI_PROXY_NO_RELOAD=1 (skip nginx reload — tests).
set -uo pipefail

ORCH_ENV="${ORCH_ENV:-$HOME/.config/ollie-orchestrator/.env}"
UNIT_DIR="${SYSTEMD_USER_DIR:-$HOME/.config/systemd/user}"
NGINX_CONF_DIR="${NGINX_CONF_DIR:-/etc/nginx/conf.d}"
NGINX_AUTH_FILE="${NGINX_AUTH_FILE:-/etc/nginx/hermes-ui-auth.conf}"
PORT_OFFSET=100

# Use sudo only when we cannot write the target ourselves. Fail LOUDLY rather
# than half-applying: a proxy that renders without its auth file 401s on every
# call, which is worse than one that was never installed.
target_parent="$(dirname "${NGINX_AUTH_FILE}")"
if [[ -w "${NGINX_CONF_DIR}" || ! -e "${NGINX_CONF_DIR}" ]] && [[ -w "${target_parent}" ]]; then
  SUDO=""
else
  if ! sudo -n true 2>/dev/null; then
    echo "ensure-hermes-ui-proxy: FATAL — need write access to ${NGINX_CONF_DIR} and ${NGINX_AUTH_FILE}, and passwordless sudo is unavailable" >&2
    exit 1
  fi
  SUDO="sudo"
fi

TOKEN="$(grep '^HERMES_DASHBOARD_TOKEN=' "${ORCH_ENV}" 2>/dev/null | tail -1 | cut -d= -f2- || true)"
if [[ -z "${TOKEN}" ]]; then
  echo "ensure-hermes-ui-proxy: FATAL — HERMES_DASHBOARD_TOKEN empty in ${ORCH_ENV}; run ensure-dashboard-token.sh first" >&2
  exit 1
fi

changed=0
write_if_changed() {  # $1=path  $2=content  $3=mode(optional)
  local path="$1" content="$2" mode="${3:-}"
  if [[ -f "${path}" ]] && [[ "$(${SUDO} cat "${path}" 2>/dev/null)" == "${content}" ]]; then
    # Content already matches. Still re-assert mode: it may have drifted
    # more permissive (restored from backup, touched by another process) and
    # this file can hold a bearer token. A mode-only fix is not a content
    # change, so it must NOT set changed=1 or trigger a reload.
    [[ -n "${mode}" ]] && ${SUDO} chmod "${mode}" "${path}"
    return 0
  fi
  ${SUDO} mkdir -p "$(dirname "${path}")"
  printf '%s' "${content}" | ${SUDO} tee "${path}" >/dev/null
  [[ -n "${mode}" ]] && ${SUDO} chmod "${mode}" "${path}"
  changed=1
  echo "ensure-hermes-ui-proxy: wrote ${path}"
}

write_if_changed "${NGINX_AUTH_FILE}" \
  "$(printf 'proxy_set_header Authorization "Bearer %s";' "${TOKEN}")" 600

# Shared map. MUST be exactly one across all rendered files — nginx rejects a
# duplicate `map` with the same name, which only shows up once a SECOND agent
# exists. This is why acceptance requires two agents.
write_if_changed "${NGINX_CONF_DIR}/hermes-ui-map.conf" \
"$(cat <<'MAP'
map $http_upgrade $hermes_ui_conn_upgrade {
    default upgrade;
    ''      close;
}
MAP
)"

shopt -s nullglob
for unit in "${UNIT_DIR}"/hermes-dashboard*.service; do
  unit_name="$(basename "${unit}")"
  agent="${unit_name#hermes-dashboard}"; agent="${agent%.service}"; agent="${agent#-}"
  [[ -z "${agent}" ]] && agent="default"

  upstream="$(grep -oE '^ExecStart=.*--port[= ]+[0-9]+' "${unit}" | grep -oE '[0-9]+$' | tail -1)"
  if [[ -z "${upstream}" ]]; then
    echo "ensure-hermes-ui-proxy: skip ${unit_name} (no --port in ExecStart)" >&2
    continue
  fi
  listen=$(( upstream + PORT_OFFSET ))

  write_if_changed "${NGINX_CONF_DIR}/hermes-ui-proxy-${agent}.conf" \
"$(cat <<CONF
# Generated by ensure-hermes-ui-proxy.sh — do not edit by hand.
# Agent: ${agent}   loopback ${listen} -> Hermes dashboard ${upstream}
# Reach it with:  ssh -L ${listen}:127.0.0.1:${listen} ollie@<box>
server {
    listen 127.0.0.1:${listen};
    server_name _;

    large_client_header_buffers 8 32k;
    client_max_body_size 20m;

    location / {
        # The session token. Without it every API route 401s.
        include ${NGINX_AUTH_FILE};

        proxy_pass http://127.0.0.1:${upstream};

        # Hermes validates Host on EVERY request (400 otherwise) and CSRF-checks
        # Origin on /api/ws, /api/events and /api/pty (403 otherwise, and the
        # chat/events/log streams then silently never connect).
        proxy_set_header Host 127.0.0.1:${upstream};
        proxy_set_header Origin http://127.0.0.1:${upstream};

        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$hermes_ui_conn_upgrade;
        proxy_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}
CONF
)"
done

if [[ "${changed}" == "1" && "${ENSURE_UI_PROXY_NO_RELOAD:-0}" != "1" ]]; then
  if ${SUDO} nginx -t 2>/dev/null; then
    # A failed reload is FATAL, not a warning. The new bearer token is already
    # on disk but the running nginx still holds the PREVIOUS one in memory, so
    # every proxied dashboard request 401s until someone reloads — the exact
    # permanent-401 failure this script exists to prevent — while an exit 0
    # here would let check-box-config.sh PASS the box.
    if ! ${SUDO} systemctl reload nginx; then
      echo "ensure-hermes-ui-proxy: FATAL — nginx reload failed; nginx is still serving the PREVIOUS token, so the UI proxy will 401 on every request until it reloads. Fix with: sudo systemctl reload nginx" >&2
      exit 1
    fi
  else
    echo "ensure-hermes-ui-proxy: FATAL — nginx -t rejected the rendered config; not reloading" >&2
    exit 1
  fi
fi
echo "ensure-hermes-ui-proxy: done (changed=${changed})"
