#!/usr/bin/env bash
# Pure stack-.env renderer. No docker/host access; reads only the old .env
# (if given) + caller-exported derived values. Sourceable + unit-testable.
# 06-install-stack.sh sources this and calls render_stack_env.

# Read one key's value from an env file (last occurrence); empty if absent.
_env_val() { [ -f "$1" ] || return 0; grep -E "^$2=" "$1" | tail -1 | cut -d= -f2- || true; }

# Resolve an operator-supplied key: exported env var > old .env value > empty.
_forward() { # VARNAME OLDENV
  local cur="${!1:-}"
  if [ -n "$cur" ]; then printf '%s' "$cur"; else _env_val "$2" "$1"; fi
}

# Carry forward keys this script does not manage but must not wipe (Fleet/operator
# writes them via set-dashboard-auth etc.).
# NOTE: Image pins (CORTEX_IMAGE, FRONTEND_IMAGE) are intentionally NOT preserved — the
# script-derived values in the heredoc are the single authoritative .env lines.
# $1 = old .env, $2 = new .env
preserve_env_keys() {
  [ -f "$1" ] || return 0
  local k line
  for k in OAUTH2_PROXY_CLIENT_ID OAUTH2_PROXY_CLIENT_SECRET OAUTH2_PROXY_COOKIE_SECRET \
           OAUTH2_PROXY_REDIRECT_URL OAUTH2_PROXY_PROVIDER OAUTH2_PROXY_EMAIL_DOMAINS \
           OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE DASHBOARD_PUBLIC_HTTPS \
           DASHBOARD_USER DASHBOARD_PASS \
           SUPABASE_URL SUPABASE_ANON_KEY SUPABASE_COOKIE_DOMAIN; do
    line=$(grep -E "^${k}=" "$1" | tail -1) && [ -n "$line" ] && echo "$line" >> "$2"
  done
  # The last iteration's status leaks as the function's exit status under set -e;
  # return 0 so a missing key never aborts the caller before chmod/up.
  return 0
}

# Write the canonical stack .env. $1 = new path, $2 = old path (or "").
render_stack_env() {
  local out="$1" old="${2:-}"
  local firecrawl hermes_ui_url vertical
  firecrawl="$(_forward FIRECRAWL_API_KEY "$old")"
  hermes_ui_url="$(_forward HERMES_UI_URL "$old")"
  vertical="$(_forward VERTICAL "$old")"
  local cortex_api_key; cortex_api_key="$(_forward CORTEX_API_KEY "$old")"
  local hermes_ui_hostname dashboard_bind hia_base_url
  hermes_ui_hostname="$(_forward HERMES_UI_HOSTNAME "$old")"
  dashboard_bind="$(_forward DASHBOARD_BIND "$old")"
  hia_base_url="$(_forward HIA_BASE_URL "$old")"
  cat > "$out" <<EOF
# Generated by 06-install-stack.sh — re-run the script to refresh.
HERMES_GATEWAY_KEY=${GATEWAY_KEY}
ORCHESTRATOR_KEY=${ORCH_KEY}
CORTEX_IMAGE=${CORTEX_IMAGE}
FRONTEND_IMAGE=${FRONTEND_IMAGE}
AGENTS_JSON=${AGENTS_JSON}
# Brain Discovery: set this to enable website crawling (uploads work without it).
FIRECRAWL_API_KEY=${firecrawl}
# Browser-facing HTTPS URL for the Hermes dashboard ("Backend Settings" link).
HERMES_UI_URL=${hermes_ui_url}
# Customer vertical slug (e.g. real-estate) — Fleet-managed; empty = generic.
VERTICAL=${vertical}
# Cortex API key. UNSET by default (open on the private Docker network). When set,
# cortex enforces it and the dashboard nginx injects it on /cortex-proxy.
CORTEX_API_KEY=${cortex_api_key}
# Operator tunables — preserved so a re-run never reverts them to compose defaults.
HERMES_UI_HOSTNAME=${hermes_ui_hostname}
DASHBOARD_BIND=${dashboard_bind}
HIA_BASE_URL=${hia_base_url}
EOF
  [ -n "$old" ] && preserve_env_keys "$old" "$out" || true
  return 0
}
