#!/usr/bin/env bash
# supabase-stack-env.sh — idempotent renderer for ~/supabase-stack/.env.
# Sourceable + unit-testable. Secrets are generated once and preserved on
# every re-run; image pins are ALWAYS restamped from the values below
# (same authority rule as stack-env.sh — never preserve pins).
set -uo pipefail

# Pinned images. Bump here (sandbox-first) — verify against the current
# supabase/docker compose (github.com/supabase/supabase/tree/master/docker)
# when bumping.
SB_DB_IMAGE_PIN="supabase/postgres:15.8.1.085"
SB_AUTH_IMAGE_PIN="supabase/gotrue:v2.177.0"
SB_REST_IMAGE_PIN="postgrest/postgrest:v12.2.12"
SB_STORAGE_IMAGE_PIN="supabase/storage-api:v1.25.7"
SB_KONG_IMAGE_PIN="kong:2.8.1"

supabase_stack_env_val() { # FILE KEY
  [ -f "$1" ] || return 0
  grep -E "^$2=" "$1" | tail -1 | cut -d= -f2- || true
}

# Resolve a secret: old .env value wins (never rotate); else from bundle.
_sb_keep() { # KEY OLDENV BUNDLE_JSON_KEY BUNDLE
  local old_v; old_v="$(supabase_stack_env_val "$2" "$1")"
  if [ -n "$old_v" ]; then printf '%s' "$old_v"; else
    printf '%s' "$4" | python3 -c "import sys,json;print(json.load(sys.stdin)['$3'])"
  fi
}

render_supabase_stack_env() { # OUT OLD
  local out="$1" old="${2:-}"
  local bundle=""
  # Generate a bundle only if any secret is missing from the old env.
  local need=0 k
  for k in POSTGRES_PASSWORD JWT_SECRET GOTRUE_JWT_KEYS JWT_JWKS ANON_KEY SERVICE_ROLE_KEY; do
    [ -z "$(supabase_stack_env_val "$old" "$k")" ] && need=1
  done
  if [ "$need" -eq 1 ]; then
    bundle="$(python3 "$(dirname "${BASH_SOURCE[0]}")/gen-supabase-keys.py")"
  fi
  local pg jwt gkeys jwks anon srk
  pg="$(_sb_keep POSTGRES_PASSWORD "$old" postgres_password "$bundle")"
  jwt="$(_sb_keep JWT_SECRET "$old" jwt_secret "$bundle")"
  gkeys="$(_sb_keep GOTRUE_JWT_KEYS "$old" gotrue_jwt_keys "$bundle")"
  jwks="$(_sb_keep JWT_JWKS "$old" jwt_jwks "$bundle")"
  anon="$(_sb_keep ANON_KEY "$old" anon_key "$bundle")"
  srk="$(_sb_keep SERVICE_ROLE_KEY "$old" service_role_key "$bundle")"
  # Operator-supplied: exported value wins, else carried forward.
  local url gid gsec
  url="${SUPABASE_PUBLIC_URL:-$(supabase_stack_env_val "$old" SUPABASE_PUBLIC_URL)}"
  gid="${GOOGLE_CLIENT_ID:-$(supabase_stack_env_val "$old" GOOGLE_CLIENT_ID)}"
  gsec="${GOOGLE_CLIENT_SECRET:-$(supabase_stack_env_val "$old" GOOGLE_CLIENT_SECRET)}"
  local genabled="false"; [ -n "$gid" ] && genabled="true"
  cat > "$out" <<EOF
# Generated by supabase-stack-env.sh — re-run 11-install-supabase.sh --deploy to refresh.
POSTGRES_PASSWORD=${pg}
JWT_SECRET=${jwt}
GOTRUE_JWT_KEYS=${gkeys}
JWT_JWKS=${jwks}
ANON_KEY=${anon}
SERVICE_ROLE_KEY=${srk}
SUPABASE_PUBLIC_URL=${url}
GOOGLE_ENABLED=${genabled}
GOOGLE_CLIENT_ID=${gid}
GOOGLE_CLIENT_SECRET=${gsec}
SB_DB_IMAGE=${SB_DB_IMAGE_PIN}
SB_AUTH_IMAGE=${SB_AUTH_IMAGE_PIN}
SB_REST_IMAGE=${SB_REST_IMAGE_PIN}
SB_STORAGE_IMAGE=${SB_STORAGE_IMAGE_PIN}
SB_KONG_IMAGE=${SB_KONG_IMAGE_PIN}
EOF
  chmod 600 "$out"
  return 0
}
