#!/usr/bin/env bash
# supabase-app-env.sh — idempotent .env renderer for APP stacks
# (templates/supabase-app). Sibling of supabase-stack-env.sh: same
# all-or-nothing rule for the 6 interdependent JWT secrets, same
# pins-always-restamped rule. Adds: STACK_NAME/KONG_PORT parameters and the
# two realtime secrets (independent of the JWT bundle — preserved
# individually, generated if absent).
set -uo pipefail

SB_DB_IMAGE_PIN="supabase/postgres:15.8.1.085"
SB_AUTH_IMAGE_PIN="supabase/gotrue:v2.177.0"
SB_REST_IMAGE_PIN="postgrest/postgrest:v12.2.12"
SB_STORAGE_IMAGE_PIN="supabase/storage-api:v1.25.7"
SB_KONG_IMAGE_PIN="kong:2.8.1"
SB_REALTIME_IMAGE_PIN="supabase/realtime:v2.102.3"

supabase_app_env_val() { # FILE KEY
  [ -f "$1" ] || return 0
  grep -E "^$2=" "$1" | tail -1 | cut -d= -f2- || true
}

_sba_keep() { # KEY OLDENV BUNDLE_JSON_KEY BUNDLE
  local old_v; old_v="$(supabase_app_env_val "$2" "$1")"
  if [ -n "$old_v" ]; then printf '%s' "$old_v"; else
    printf '%s' "$4" | python3 -c "import sys,json;print(json.load(sys.stdin)['$3'])"
  fi
}

_sba_keep_or_gen() { # KEY OLDENV NBYTES  (hex output, 2*NBYTES chars)
  local old_v; old_v="$(supabase_app_env_val "$2" "$1")"
  if [ -n "$old_v" ]; then printf '%s' "$old_v"; else
    python3 -c "import secrets;print(secrets.token_hex($3))"
  fi
}

render_supabase_app_env() { # OUT OLD  (exports: STACK_NAME KONG_PORT SUPABASE_PUBLIC_URL SITE_URL)
  local out="$1" old="${2:-}"
  local bundle="" present=0 missing_keys="" k
  for k in POSTGRES_PASSWORD JWT_SECRET GOTRUE_JWT_KEYS JWT_JWKS ANON_KEY SERVICE_ROLE_KEY; do
    if [ -n "$(supabase_app_env_val "$old" "$k")" ]; then present=$((present + 1))
    else missing_keys="${missing_keys}${missing_keys:+ }$k"; fi
  done
  if [ "$present" -eq 0 ]; then
    bundle="$(python3 "$(dirname "${BASH_SOURCE[0]}")/gen-supabase-keys.py")"
  elif [ "$present" -lt 6 ]; then
    echo "ERROR: $old has some but not all of the 6 interdependent Supabase secrets (missing: $missing_keys) — restore from backup or delete the .env to regenerate the full set." >&2
    return 1
  fi
  local pg jwt gkeys jwks anon srk renc rskb
  pg="$(_sba_keep POSTGRES_PASSWORD "$old" postgres_password "$bundle")"
  jwt="$(_sba_keep JWT_SECRET "$old" jwt_secret "$bundle")"
  gkeys="$(_sba_keep GOTRUE_JWT_KEYS "$old" gotrue_jwt_keys "$bundle")"
  jwks="$(_sba_keep JWT_JWKS "$old" jwt_jwks "$bundle")"
  anon="$(_sba_keep ANON_KEY "$old" anon_key "$bundle")"
  srk="$(_sba_keep SERVICE_ROLE_KEY "$old" service_role_key "$bundle")"
  renc="$(_sba_keep_or_gen REALTIME_ENC_KEY "$old" 8)"        # 16 hex chars (AES key len realtime expects)
  rskb="$(_sba_keep_or_gen REALTIME_SECRET_KEY_BASE "$old" 32)"
  local name port url site_url
  name="${STACK_NAME:-$(supabase_app_env_val "$old" STACK_NAME)}"
  port="${KONG_PORT:-$(supabase_app_env_val "$old" KONG_PORT)}"
  url="${SUPABASE_PUBLIC_URL:-$(supabase_app_env_val "$old" SUPABASE_PUBLIC_URL)}"
  site_url="${SITE_URL:-$(supabase_app_env_val "$old" SITE_URL)}"
  for k in name port url site_url; do
    if [ -z "${!k}" ]; then echo "ERROR: ${k} unset (export STACK_NAME/KONG_PORT/SUPABASE_PUBLIC_URL/SITE_URL or provide in OLD env)" >&2; return 1; fi
  done
  cat > "$out" <<EOF
# Generated by supabase-app-env.sh — re-run 20-install-app-stack.sh to refresh.
STACK_NAME=${name}
KONG_PORT=${port}
POSTGRES_PASSWORD=${pg}
JWT_SECRET=${jwt}
GOTRUE_JWT_KEYS=${gkeys}
JWT_JWKS=${jwks}
ANON_KEY=${anon}
SERVICE_ROLE_KEY=${srk}
REALTIME_ENC_KEY=${renc}
REALTIME_SECRET_KEY_BASE=${rskb}
SUPABASE_PUBLIC_URL=${url}
SITE_URL=${site_url}
SB_DB_IMAGE=${SB_DB_IMAGE_PIN}
SB_AUTH_IMAGE=${SB_AUTH_IMAGE_PIN}
SB_REST_IMAGE=${SB_REST_IMAGE_PIN}
SB_STORAGE_IMAGE=${SB_STORAGE_IMAGE_PIN}
SB_KONG_IMAGE=${SB_KONG_IMAGE_PIN}
SB_REALTIME_IMAGE=${SB_REALTIME_IMAGE_PIN}
EOF
  chmod 600 "$out"
  return 0
}
