#!/usr/bin/env bash
# 06-install-stack.sh — install the Docker stack (cortex + ollie-dashboard).
#
# Run as: the service user (ollie by default; in the `docker` group)
# Idempotent: safe to re-run.
#
# What it does:
#   1. Creates ~/hermes-stack/ with docker-compose.yml (vendored from frontend repo)
#   2. Writes ~/hermes-stack/.env populated from existing host config:
#        - HERMES_GATEWAY_KEY ← ~/.hermes/.env's API_SERVER_KEY
#        - ORCHESTRATOR_KEY   ← ~/.config/ollie-orchestrator/.env's value
#        - AGENTS_JSON        ← auto-built by walking installed profiles
#   3. docker compose pull + up -d
#   4. Verifies the dashboard responds on :3000

set -euo pipefail

if [[ "$(id -u)" -eq 0 ]]; then
  echo "error: run as the service user, not root" >&2
  exit 1
fi
if ! id -nG | grep -qw docker; then
  echo "error: service user not in docker group — log out and back in after running 01-bootstrap.sh" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_SRC="${SCRIPT_DIR}/../templates/docker-compose.yml"
STACK_DIR="${HOME}/hermes-stack"
STACK_ENV="${STACK_DIR}/.env"
HERMES_ENV="${HOME}/.hermes/.env"
ORCH_ENV="${HOME}/.config/ollie-orchestrator/.env"

echo "==> step 1: stage ${STACK_DIR}/docker-compose.yml"
mkdir -p "${STACK_DIR}"
cp "${COMPOSE_SRC}" "${STACK_DIR}/docker-compose.yml"

echo "==> step 2: derive secrets from host config"
if [[ ! -f "${HERMES_ENV}" ]]; then
  echo "error: ${HERMES_ENV} missing — run 02-install-hermes.sh first" >&2; exit 1
fi
if [[ ! -f "${ORCH_ENV}" ]]; then
  echo "error: ${ORCH_ENV} missing — run 05-install-orchestrator.sh first" >&2; exit 1
fi
GATEWAY_KEY="$(grep '^API_SERVER_KEY=' "${HERMES_ENV}" | cut -d= -f2-)"
ORCH_KEY="$(grep '^ORCHESTRATOR_KEY=' "${ORCH_ENV}" | cut -d= -f2-)"

echo "==> step 3: build AGENTS_JSON by auto-detecting installed profiles"
# Default profile is always present. Use its port from .env. Display name defaults to "Ollie".
DEFAULT_PORT="$(grep '^API_SERVER_PORT=' "${HERMES_ENV}" | cut -d= -f2-)"
DEFAULT_DASH=9119
# Build JSON entries. jq isn't a hard dep for this — we hand-roll the JSON for portability.
build_entry() {
  local id="$1" name="$2" gw="$3" dash="$4"
  printf '{"id":"%s","name":"%s","gatewayUrl":"http://host.docker.internal:%s","dashboardUrl":"http://host.docker.internal:%s"}' \
    "${id}" "${name}" "${gw}" "${dash}"
}
ENTRIES=()
ENTRIES+=("$(build_entry default Ollie "${DEFAULT_PORT}" "${DEFAULT_DASH}")")
for prof_env in "${HOME}"/.hermes/profiles/*/.env; do
  [[ -f "${prof_env}" ]] || continue
  prof_name="$(basename "$(dirname "${prof_env}")")"
  gw_port="$(grep '^API_SERVER_PORT=' "${prof_env}" | cut -d= -f2-)"
  # Resolve the dashboard port from the systemd unit ExecStart line.
  unit="${HOME}/.config/systemd/user/hermes-dashboard-${prof_name}.service"
  if [[ -f "${unit}" ]]; then
    dash_port="$(grep -oE -- '--port [0-9]+' "${unit}" | awk '{print $2}' | head -1)"
  else
    dash_port=""
  fi
  if [[ -z "${gw_port}" || -z "${dash_port}" ]]; then
    echo "    skipping profile '${prof_name}' (missing port info)" >&2
    continue
  fi
  display="$(echo "${prof_name}" | sed 's/.*/\u&/')"
  ENTRIES+=("$(build_entry "${prof_name}" "${display}" "${gw_port}" "${dash_port}")")
done
# Join entries with commas
AGENTS_JSON="[$(IFS=,; echo "${ENTRIES[*]}")]"
echo "    detected agents: $(echo "${AGENTS_JSON}" | python3 -c 'import sys,json; print(", ".join(a["id"] for a in json.load(sys.stdin)))')"

# FIRECRAWL_API_KEY is operator-supplied (for Brain Discovery web crawl), not derived from
# host config — preserve any value already set so re-running this script never wipes it.
# Precedence: env var > existing .env value > empty.
EXISTING_FIRECRAWL="$(grep -E '^FIRECRAWL_API_KEY=' "${STACK_ENV}" 2>/dev/null | cut -d= -f2- || true)"
FIRECRAWL_API_KEY="${FIRECRAWL_API_KEY:-${EXISTING_FIRECRAWL}}"

# HERMES_UI_URL is operator-supplied (browser-facing TLS URL for the native Hermes
# dashboard, used by the frontend's "Backend Settings" link). Same precedence as
# FIRECRAWL_API_KEY: env var > existing .env value > empty. Unset is safe — the link
# falls back to http://<host>:9119, which HTTPS-First browsers reject; set this to a
# TLS reverse-proxy to :9119 (e.g. https://<host>:9443) to fix that.
EXISTING_HERMES_UI_URL="$(grep -E '^HERMES_UI_URL=' "${STACK_ENV}" 2>/dev/null | cut -d= -f2- || true)"
HERMES_UI_URL="${HERMES_UI_URL:-${EXISTING_HERMES_UI_URL}}"

echo "==> step 4: write ${STACK_ENV} (rewrites every run to keep it canonical)"
cat > "${STACK_ENV}" <<EOF
# Generated by 06-install-stack.sh — re-run the script to refresh.
HERMES_GATEWAY_KEY=${GATEWAY_KEY}
ORCHESTRATOR_KEY=${ORCH_KEY}
AGENTS_JSON=${AGENTS_JSON}
# Brain Discovery: set this to enable website crawling (uploads work without it).
FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
# Browser-facing TLS URL for the native Hermes dashboard ("Backend Settings" link).
# Unset → link falls back to http://<host>:9119, which HTTPS-First browsers reject.
HERMES_UI_URL=${HERMES_UI_URL}
EOF
chmod 600 "${STACK_ENV}"

echo "==> step 5: docker compose pull + up -d"
docker compose -f "${STACK_DIR}/docker-compose.yml" pull --quiet
docker compose -f "${STACK_DIR}/docker-compose.yml" up -d

echo
echo "==> verification (give nginx 5s to finish its agents.conf regen)"
sleep 5
set +e
echo "    container state:"
docker compose -f "${STACK_DIR}/docker-compose.yml" ps --format 'table {{.Service}}\t{{.Status}}'
code=$(curl -s -o /dev/null -w '%{http_code}' -m 5 http://localhost:3000/)
echo "    dashboard http :3000 → ${code:-no response} ($([ "${code}" = "200" ] && echo "✓" || echo "expected 200"))"
code=$(curl -s -o /dev/null -w '%{http_code}' -m 5 http://localhost:9120/health)
echo "    cortex    http :9120/health → ${code:-no response} ($([ "${code}" = "200" ] && echo "✓" || echo "expected 200"))"
if [[ -z "${FIRECRAWL_API_KEY}" ]]; then
  echo "    note: Brain Discovery web crawl is disabled — set FIRECRAWL_API_KEY in ${STACK_ENV}"
  echo "          (or export it and re-run) to enable website crawling. Document uploads work without it."
fi
if [[ -z "${HERMES_UI_URL}" ]]; then
  echo "    note: HERMES_UI_URL unset — the dashboard's \"Backend Settings\" link points to"
  echo "          http://<host>:9119, which HTTPS-First browsers reject (ERR_SSL_PROTOCOL_ERROR)."
  echo "          Set HERMES_UI_URL in ${STACK_ENV} to a TLS reverse-proxy of :9119 to fix it."
fi
set -e

echo
echo "✓ Stack installed and running."
echo
echo "Open in your browser: http://<this-host-ip>:3000/chat"
